apiVersion: v1                 # Specifies the API version
kind: Pod                      # Specifies that this is a Pod resource
metadata:
  name: nginxpod               # The name of the Pod
  labels:
    app: myapp                 # Label for the Pod
spec:
  containers:
    - name: nginxcontainer     # Name of the container
      image: nginx             # Docker image to use
      ports:
        - containerPort: 80    # The port exposed by the container